-- 코드를 입력하세요
SELECT a.AUTHOR_ID AS AUTHOR_ID, a.AUTHOR_NAME AS AUTHOR_NAME, result.CATEGORY AS CATEGORY, SUM(result.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR a JOIN
(
    SELECT b.BOOK_ID AS BOOK_ID, b.category AS CATEGORY, b.author_id AS AUTHOR_ID, SUM(s.SALES)*b.PRICE AS TOTAL_SALES
    FROM BOOK b JOIN BOOK_SALES s 
    ON b.BOOK_ID = s.BOOK_ID
    WHERE TO_CHAR(s.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY b.BOOK_ID, b.category, b.author_id, b.PRICE
) result
ON a.AUTHOR_ID = result.AUTHOR_ID
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, result.CATEGORY
ORDER BY a.AUTHOR_ID ASC, result.CATEGORY DESC;
