WITH HISTORY AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < TO_DATE('2022-12-01', 'YYYY-MM-DD') 
      AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
),
RATE AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
      AND CAR_TYPE IN ('세단', 'SUV')
)

SELECT 
  cr.CAR_ID, 
  cr.CAR_TYPE, 
  cr.DAILY_FEE * 30 * ((100 - r.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR cr 
JOIN RATE r ON cr.CAR_TYPE = r.CAR_TYPE 
WHERE NOT EXISTS (
    SELECT 1 
    FROM HISTORY h 
    WHERE h.CAR_ID = cr.CAR_ID
)
AND cr.CAR_TYPE IN ('세단', 'SUV')
AND cr.DAILY_FEE * 30 * ((100 - r.DISCOUNT_RATE)/100) >= 500000
AND cr.DAILY_FEE * 30 * ((100 - r.DISCOUNT_RATE)/100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
