-- 코드를 입력하세요
SELECT i.REST_ID AS REST_ID, i.REST_NAME AS REST_NAME, i.FOOD_TYPE AS FOOD_TYPE, i.FAVORITES AS FAVORITES, i.ADDRESS AS ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO i
JOIN REST_REVIEW r
ON i.REST_ID = r.REST_ID
WHERE ADDRESS LIKE '%서울시%' OR ADDRESS LIKE '%서울특별시%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;