-- 코드를 입력하세요
with JOIN_COUNT AS (
    SELECT COUNT(*) AS TOTAL_JOIN_COUNT
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)

SELECT EXTRACT(YEAR FROM o.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM o.SALES_DATE) AS MONTH, 
COUNT(DISTINCT o.USER_ID) AS PURCHASE_USERS, ROUND(COUNT(DISTINCT o.USER_ID) * 1.0 / jc.TOTAL_JOIN_COUNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE o
JOIN USER_INFO u
ON o.USER_ID = u.USER_ID AND TO_CHAR(u.JOINED, 'YYYY') = '2021'
LEFT JOIN JOIN_COUNT jc
ON 1=1
GROUP BY EXTRACT(YEAR FROM o.SALES_DATE), EXTRACT(MONTH FROM o.SALES_DATE), jc.TOTAL_JOIN_COUNT
ORDER BY YEAR ASC, MONTH ASC;