-- 코드를 입력하세요
with CAR_RENTAL_DURATION AS (
    SELECT h.HISTORY_ID, h.CAR_ID, c.CAR_TYPE, c.DAILY_FEE,
    CASE WHEN (END_DATE - START_DATE + 1) BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN (END_DATE - START_DATE + 1) BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
        ELSE '7일 미만'
    END AS DURATION_TYPE,
    END_DATE - START_DATE + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)


SELECT d.HISTORY_ID AS HISTORY_ID, d.DAILY_FEE * d.DURATION * ((100 - NVL(p.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_DURATION d
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON d.CAR_TYPE = p.CAR_TYPE AND d.DURATION_TYPE = p.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;