WITH JULY_SALES AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
), FIRST_HALF_SALES AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT j.FLAVOR
FROM JULY_SALES j JOIN FIRST_HALF_SALES f
ON j.FLAVOR = f.FLAVOR
ORDER BY (j.TOTAL + f.TOTAL) DESC
FETCH FIRST 3 ROWS ONLY;