-- 코드를 입력하세요
-- NULL이거나 2022년 4월 13일 이후이거나

SELECT a.APNT_NO AS APNT_NO, 
p.PT_NAME AS PT_NAME,
p.PT_NO AS PT_NO, 
a.MCDP_CD AS MCDP_CD, 
d.DR_NAME AS DR_NAME,
a.APNT_YMD as APNT_YMD
FROM APPOINTMENT a 
JOIN PATIENT p ON a.PT_NO = p.PT_NO 
JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE a.MCDP_CD = 'CS' 
    AND TO_CHAR(a.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
    AND a.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;